NaturalGeographicFeatures:
  - Mountain:
      FeatureClass: 110000
      FeatureName: Mountain
  - WaterBody:
      FeatureClass: 120000
      FeatureName: WaterBody
  - SnowArea:
      FeatureClass: 130000
      FeatureName: SnowArea
  - Ocean:
      FeatureClass: 140000
      FeatureName: Ocean
  - Relief:
      FeatureClass: 150000
      FeatureName: Relief
  - PhysicalField:
      FeatureClass: 160000
      FeatureName: PhysicalField      
ArtificialGeographicFeatures:
  - AgriculturalArea:
      FeatureClass: 210000
      FeatureName: AgriculturalArea
  - WaterFacility:
      FeatureClass: 220000
      FeatureName: WaterFacility
  - TransportationFacility:
      FeatureClass: 230000
      FeatureName: TransportationFacility
  - Building:
      FeatureClass: 240000
      FeatureName: Building
  - Pipeline:
      FeatureClass: 250000
      FeatureName: Pipeline
  - Courtyard:
      FeatureClass: 260000
      FeatureName: Courtyard
  - ArtificialLandform:
      FeatureClass: 270000
      FeatureName: ArtificialLandform
